name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering of the workflow
permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set git config for long paths
        run: git config --system core.longpaths true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo
        run: cargo build --release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: tool
          path: target\release\tool.exe

      - name: Set date
        id: set-date
        shell: pwsh
        run: |
          $CURRENT_DATE = Get-Date -UFormat "%Y.%m.%d"
          echo "CURRENT_DATE=$CURRENT_DATE" >> $env:GITHUB_ENV
          echo "CURRENT_DATE=$CURRENT_DATE" >> $env:GITHUB_OUTPUT

      - name: Release Nightly
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/auto-release')
        with:
          name: Nightly ${{ steps.set-date.outputs.CURRENT_DATE }}
          body: Automated nightly release of tool
          tag_name: "nightly-${{ steps.set-date.outputs.CURRENT_DATE }}"
          prerelease: true
          files: |
            target/release/tool.exe
